In [6]:
import torch  

torch.randint??

Docstring:
randint(low=0, high, size, \*, generator=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor

Returns a tensor filled with random integers generated uniformly
between :attr:`low` (inclusive) and :attr:`high` (exclusive).

The shape of the tensor is defined by the variable argument :attr:`size`.

.. note::
    With the global dtype default (``torch.float32``), this function returns
    a tensor with dtype ``torch.int64``.

Args:
    low (int, optional): Lowest integer to be drawn from the distribution. Default: 0.
    high (int): One above the highest integer to be drawn from the distribution.
    size (tuple): a tuple defining the shape of the output tensor.

Keyword args:
    generator (:class:`torch.Generator`, optional): a pseudorandom number generator for sampling
    out (Tensor, optional): the output tensor.
    dtype (`torch.dtype`, optional) - the desired data type of returned tensor. Default: if ``None``,
        this functi

In [8]:
torch.randint(low= 10, high= 13, size=(2, 4))

tensor([[11, 10, 11, 11],
        [10, 10, 10, 11]])

In [14]:
torch.stack??

Docstring:
stack(tensors, dim=0, *, out=None) -> Tensor

Concatenates a sequence of tensors along a new dimension.

All tensors need to be of the same size.

.. seealso::

    :func:`torch.cat` concatenates the given sequence along an existing dimension.

Arguments:
    tensors (sequence of Tensors): sequence of tensors to concatenate
    dim (int, optional): dimension to insert. Has to be between 0 and the number
        of dimensions of concatenated tensors (inclusive). Default: 0

Keyword args:
    out (Tensor, optional): the output tensor.

Example::

    >>> x = torch.randn(2, 3)
    >>> x
    tensor([[ 0.3367,  0.1288,  0.2345],
            [ 0.2303, -1.1229, -0.1863]])
    >>> x = torch.stack((x, x)) # same as torch.stack((x, x), dim=0)
    >>> x
    tensor([[[ 0.3367,  0.1288,  0.2345],
             [ 0.2303, -1.1229, -0.1863]],

            [[ 0.3367,  0.1288,  0.2345],
             [ 0.2303, -1.1229, -0.1863]]])
    >>> x.size()
    torch.Size([2, 2, 3])
    >>> x = torch.sta

In [22]:
import torch  
var = torch.rand(3,2)
var

tensor([[0.6927, 0.5565],
        [0.7286, 0.7987],
        [0.4266, 0.5485]])

In [23]:
print(var.shape)

torch.Size([3, 2])


In [33]:
stacked_1 = torch.stack((var, var, var))
stacked_1

tensor([[[0.6927, 0.5565],
         [0.7286, 0.7987],
         [0.4266, 0.5485]],

        [[0.6927, 0.5565],
         [0.7286, 0.7987],
         [0.4266, 0.5485]],

        [[0.6927, 0.5565],
         [0.7286, 0.7987],
         [0.4266, 0.5485]]])

In [34]:
stacked_1.shape

torch.Size([3, 3, 2])

In [35]:
stacked_2 = torch.stack((var, var, var), dim= 2)
stacked_2

tensor([[[0.6927, 0.6927, 0.6927],
         [0.5565, 0.5565, 0.5565]],

        [[0.7286, 0.7286, 0.7286],
         [0.7987, 0.7987, 0.7987]],

        [[0.4266, 0.4266, 0.4266],
         [0.5485, 0.5485, 0.5485]]])