In [8]:
torch.stack??

Docstring:
stack(tensors, dim=0, *, out=None) -> Tensor

Concatenates a sequence of tensors along a new dimension.

All tensors need to be of the same size.

.. seealso::

    :func:`torch.cat` concatenates the given sequence along an existing dimension.

Arguments:
    tensors (sequence of Tensors): sequence of tensors to concatenate
    dim (int, optional): dimension to insert. Has to be between 0 and the number
        of dimensions of concatenated tensors (inclusive). Default: 0

Keyword args:
    out (Tensor, optional): the output tensor.

Example::

    >>> x = torch.randn(2, 3)
    >>> x
    tensor([[ 0.3367,  0.1288,  0.2345],
            [ 0.2303, -1.1229, -0.1863]])
    >>> x = torch.stack((x, x)) # same as torch.stack((x, x), dim=0)
    >>> x
    tensor([[[ 0.3367,  0.1288,  0.2345],
             [ 0.2303, -1.1229, -0.1863]],

            [[ 0.3367,  0.1288,  0.2345],
             [ 0.2303, -1.1229, -0.1863]]])
    >>> x.size()
    torch.Size([2, 2, 3])
    >>> x = torch.sta

In [1]:
import torch  
var = torch.rand(2, 3 ,2)
var

tensor([[[0.3588, 0.0119],
         [0.5013, 0.6860],
         [0.8304, 0.6770]],

        [[0.7968, 0.9089],
         [0.9247, 0.4923],
         [0.2146, 0.1891]]])

In [2]:
print(var.shape)

torch.Size([2, 3, 2])


In [3]:
stacked_1 = torch.stack((var, var, var))
stacked_1

tensor([[[[0.3588, 0.0119],
          [0.5013, 0.6860],
          [0.8304, 0.6770]],

         [[0.7968, 0.9089],
          [0.9247, 0.4923],
          [0.2146, 0.1891]]],


        [[[0.3588, 0.0119],
          [0.5013, 0.6860],
          [0.8304, 0.6770]],

         [[0.7968, 0.9089],
          [0.9247, 0.4923],
          [0.2146, 0.1891]]],


        [[[0.3588, 0.0119],
          [0.5013, 0.6860],
          [0.8304, 0.6770]],

         [[0.7968, 0.9089],
          [0.9247, 0.4923],
          [0.2146, 0.1891]]]])

In [4]:
stacked_1.shape

torch.Size([3, 2, 3, 2])

In [5]:
var, var.shape

(tensor([[[0.3588, 0.0119],
          [0.5013, 0.6860],
          [0.8304, 0.6770]],
 
         [[0.7968, 0.9089],
          [0.9247, 0.4923],
          [0.2146, 0.1891]]]),
 torch.Size([2, 3, 2]))

In [6]:
stacked_2 = torch.stack((var, var), dim=1)
print(stacked_2.shape)
stacked_2

torch.Size([2, 2, 3, 2])


tensor([[[[0.3588, 0.0119],
          [0.5013, 0.6860],
          [0.8304, 0.6770]],

         [[0.3588, 0.0119],
          [0.5013, 0.6860],
          [0.8304, 0.6770]]],


        [[[0.7968, 0.9089],
          [0.9247, 0.4923],
          [0.2146, 0.1891]],

         [[0.7968, 0.9089],
          [0.9247, 0.4923],
          [0.2146, 0.1891]]]])