In [1]:
import numpy as np

In [2]:
np.random??

Type:        module
String form: <module 'numpy.random' from 'c:\\Users\\ADMIN\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\numpy\\random\\__init__.py'>
File:        c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\numpy\random\__init__.py
Source:     
"""
Random Number Generation

Use ``default_rng()`` to create a `Generator` and call its methods.

=============== =========================================================
Generator
--------------- ---------------------------------------------------------
Generator       Class implementing all of the random number distributions
default_rng     Default constructor for ``Generator``
=============== =========================================================

============================================= ===
BitGenerator Streams that work with Generator
--------------------------------------------- ---
MT19937
PCG64
PCG64DXSM
Philox
SFC64
============================================= ===

==========

In [6]:
np.random.random??

Docstring:
random(size=None)

Return random floats in the half-open interval [0.0, 1.0). Alias for
`random_sample` to ease forward-porting to the new random API.
Type:      builtin_function_or_method

In [7]:
random = np.random.random((2, 3))
random

array([[0.9644947 , 0.03796608, 0.03638135],
       [0.96478446, 0.40177491, 0.88495568]])

In [9]:
np.random.randint??

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Outp

In [12]:
randi= np.random.randint(low=10, high= 15, size=(10, 2))
randi

array([[12, 10],
       [10, 10],
       [12, 10],
       [12, 14],
       [14, 12],
       [12, 11],
       [12, 14],
       [10, 13],
       [12, 12],
       [13, 12]])

In [13]:
np.random.randn??

Docstring:
randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

.. note::
    New code should use the
    `~numpy.random.Generator.standard_normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    I

In [29]:
rands = np.random.randn(5, 4)
rands

array([[-0.34546919, -0.02767814,  0.19101044, -0.10971586],
       [-0.24818121,  1.82439279,  0.53176284,  0.35426741],
       [ 0.47307262,  1.46505279,  0.27490707,  0.00592524],
       [-0.67747101,  1.58025168, -0.22911637, -1.93879506],
       [-0.77746212, -0.56390415,  0.42945432, -2.1114076 ]])

In [30]:
rands.std()

0.9681086272813886

In [31]:
rands.mean()

0.005044823610858051