In [1]:
import numpy as np

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

rows = [0, 2]  # First and third rows
cols = [1, 2]  # Second and third columns

row_indices, col_indices = np.ix_(rows, cols)

# Use the indices to select the subarray
subarray = array[row_indices, col_indices]

print(subarray)


[[2 3]
 [8 9]]


In [4]:
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [26]:
ixgrid = np.ix_([0, 1, 0], [2, 4, 3])
ixgrid

(array([[0],
        [1],
        [0]]),
 array([[2, 4, 3]]))

In [27]:
ixgrid[0].shape, ixgrid[1].shape

((3, 1), (1, 3))

In [28]:
a[ixgrid]

array([[2, 4, 3],
       [7, 9, 8],
       [2, 4, 3]])

In [29]:
ixgrid = np.ix_([True, True], [2, 4])
ixgrid

(array([[0],
        [1]], dtype=int64),
 array([[2, 4]]))

In [18]:
ixgrid = np.ix_([True, True], [False, False, True, False, True])

In [19]:
ixgrid

(array([[0],
        [1]], dtype=int64),
 array([[2, 4]], dtype=int64))